name: Build
on:
  push:
    branches:
      - main
      - release/*
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov selenium playwright
      - name: Running pytest
        run: |
          pytest -v  --cov --cov-report=xml:tests/coverage.xml --cov-report=html
          pwd
          ls -lash
          cd tests
          ls -lash
          cd ../SampleCalculatorUtils
          ls -lash
          cd ../SampleTriangleUtils
          ls -lash
      - name: Analysing the code with pylint
        continue-on-error: true
        run: |
          pylint main.py --output-format=parseable > pylint.txt
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
